---
- name: Copy SSL cert
  copy:
    src: "{{ item.value.ssl.cert }}"
    dest: "{{ nginx_ssl_path }}/{{ item.value.ssl.cert | basename }}"
    mode: 0640
  with_dict: "{{ static_sites }}"
  when: ssl_enabled and item.value.ssl.cert is defined
  notify: reload nginx

- name: Copy SSL key
  copy:
    src: "{{ item.value.ssl.key }}"
    dest: "{{ nginx_ssl_path }}/{{ item.value.ssl.key | basename }}"
    mode: 0600
  with_dict: "{{ static_sites }}"
  when: ssl_enabled and item.value.ssl.key is defined
  notify: reload nginx

# - include: "{{ playbook_dir }}/roles/common/tasks/disable_challenge_sites.yml"
- name: disable temporary challenge sites
  file:
    path: "{{ nginx_path }}/sites-enabled/letsencrypt-{{ item }}.conf"
    state: absent
  with_items: "{{ static_sites.keys() }}"
  notify: reload nginx

- name: Create Nginx conf for challenges location
  template:
    src: "{{ playbook_dir }}/roles/letsencrypt/templates/acme-challenge-location.conf.j2"
    dest: "{{ nginx_path }}/acme-challenge-location.conf"
  notify: reload nginx

- name: Create static site configuration for Nginx
  template:
    src: "{{ item.value.nginx_static_site_conf | default(nginx_static_site_conf) }}"
    dest: "{{ nginx_path }}/sites-available/{{ item.key }}.conf"
  with_dict: "{{ static_sites }}"
  notify: reload nginx
  tags: nginx-includes

- name: Enable static site
  file:
    src: "{{ nginx_path }}/sites-available/{{ item.key }}.conf"
    dest: "{{ nginx_path }}/sites-enabled/{{ item.key }}.conf"
    owner: root
    group: root
    state: link
  with_dict: "{{ static_sites }}"
  notify: reload nginx
